### ISSUE TITLE
Alternative for route handling?

### ISSUE THREAD

**Issue by dfernandez79** [cyclejs/todomvc-cycle#10]
This line in src/intents/todos.js:

```
changeRoute$: Rx.Observable.fromEvent(window, 'hashchange')
```

breaks the concept of response observables comming from the user, I think that the hashchange event should come from the domDriver or other driver. It also makes testing hard, and adds a global reference that is not declared.

**Comment by staltz** [comment]
You are right and it needs to be fixed.

**Comment by staltz** [comment]
Fixed with a very lightweight driver.
