### ISSUE TITLE
todomvc-cycle becomes very slow with a lot of items (blocking script)

### ISSUE THREAD

**Issue by sebastiendavid** [cyclejs/todomvc-cycle#22]
Hi,

First: congrats for the job done with cycle.js, I like the ideas behind this framework.

Now the problem I see is about a list with a lot of children observed by RxJS. In this todomvc example you can fill the localstorage with 2000 items, and see by yourself.

Here the way I produce the slowness by executing this in my developer tools and refreshing the page:

```
var store = { list: [] };
for (var i = 1; i <= 2000; i++) {
  store.list.push({ title: 'Todo' + i, completed: false, id: i });
}
localStorage.setItem('todos-cycle', JSON.stringify(store));
```

After this, complete a todo by clicking on it, and you can see a lot of scripting (mostly RxJS stuff):

<img width="1440" alt="screen shot 2016-01-23 at 17 43 41" src="https://cloud.githubusercontent.com/assets/1570879/12531472/eef2bec4-c1fb-11e5-918a-369d68811153.png">

Of course I think that 2000 todos is a little dumb :D, but maybe it make sense in another kind of app.

**Comment by staltz** [comment]
Thanks, we'll revise this once we get Cycle working with RxJS 5 and most.js.

**Comment by Frikki** [comment]
Is this still relevant?

**Comment by sebastiendavid** [comment]
I just tested it, it's a lot better 👍
