### ISSUE TITLE
Question about the views

### ISSUE THREAD

**Issue by Bretto** [cyclejs/todomvc-cycle#24]
Congrats on your Framework, I followed the egghead tuts and i am very interested in the Cyclejs paradigm. So my question is: Can you use an abstraction/framework on the view layer so you don't have to write your view in JS ? I prefer writing them in plain html and using "something" to pass in the values and do the mutations... Is this possible with Cyclesjs ?

**Comment by staltz** [comment]
@Bretto hi, the support for that type of approach isn't strong, but it is possible, see for instance this repository https://github.com/tetsuo/virtual-stache. You can build your own solution too.
