### ISSUE TITLE
Feature Request: Use cycle-history

### ISSUE THREAD

**Issue by donaldpipowitch** [cyclejs/todomvc-cycle#26]
Hi,

in my opinion it would be nice, if `todomvc-cycle` could use `cycle-history` instead of the more custom `initialHash`/`hashchange`. I'd expect to see how to use "offical" modules ("official" in the sense of "a module in the https://github.com/cyclejs organisation") in this example to check how they can be used together (e.g. what is an idiomatic Cycle application?).

**Comment by staltz** [comment]
Good idea. Things move quite quickly so it's hard to keep all the examples up-to-date with the latest best practices, but still, we can do this.

**Comment by TylorS** [comment]
This is done with #28
