### ISSUE TITLE
Website link to this project is broken

### ISSUE THREAD

**Issue by frangio** [cyclejs/todomvc-cycle#40]
With the site redesign the app seems to be gone.

**Comment by staltz** [comment]
Very good point. We need to fix that.

**Comment by cluelessjoe** [comment]
Is this issue about https://cycle.js.org/todomvc-cycle/ being dead or something else? => https://cycle.js.org/todomvc-cycle/ is for sure dead and it's a pity IMHO :$

**Comment by vkammerer** [comment]
Yes but https://cyclejs.github.io/todomvc-cycle/ is well alive, and the URL makes it easy for developers who know github to find the corresponding repo.
https://github.com/cyclejs/todomvc-cycle/pull/41 fixes it
