### ISSUE TITLE
Here's an injection flow diagram if you want it

### ISSUE THREAD

**Issue by jaredly** [cyclejs/todomvc-cycle#5]
I threw this together to help me grok was was going on. It might be useful to other people too.

![todomvc-cycle-injection](https://cloud.githubusercontent.com/assets/112170/6583107/8f0202d8-c727-11e4-8ea3-65f92e67fd45.png)

**Comment by staltz** [comment]
:+1: Shall we put this on the README.md?

**Comment by jaredly** [comment]
sure, I'll PR
