### ISSUE TITLE
Show completed bug

### ISSUE THREAD

**Issue by zigomir** [cyclejs/todomvc-cycle#7]
![cycle-mvc-bug](https://cloud.githubusercontent.com/assets/957321/6930783/aa980c0a-d806-11e4-9cee-a0c6f0821a12.gif)

Was just looking around and found that one.

**Comment by staltz** [comment]
Thanks @zigomir . I think updating to the most recent Cycle version might fix it. I'll do that

**Comment by staltz** [comment]
Fixed by updating Cycle to 0.18.1. Can you verify @zigomir that it is now fine on your side?

**Comment by zigomir** [comment]
Cool. Works fine now.
